linux-toradex-4.1-2.0.x: fix generic defconfig
linux-toradex-4.1-2.0.x/defconfig is not building for machine
apalis-imx6, colibri-imx6, or colibri-imx7.
But the kernel does not (no longer`) build for this configuration.

|   LD      init/built-in.o
| drivers/built-in.o: In function `mxc_hdmi_disp_init':
| coresight-etm-cp14.c:(.text+0x4499c): undefined reference to `mxc_cea_mode'
| ...

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
Acked-by: Stefan Agner <stefan.agner@toradex.com>