imx-atf: fix a uninitialized variable issue
This fixes a following compiling error on verdin-imx8mm machine:
+| plat/imx/common/imx8m/imx_rdc.c: In function 'imx_rdc_set_masters':
+| plat/imx/common/imx8m/imx_rdc.c:146:9: error: 'ret' may be used uninitialized in this function [-Werror=maybe-uninitialized]

Signed-off-by: Ming Liu <ming.liu@toradex.com>
(cherry picked from commit af3c4735e6f2bfd3c1166a434832286a281a7d65)