linux-imx-headers_5%.bbappend: keep deploying ion.h
meta-freescale moved to a newer kernel which no longer deploys ion.h.
This no leads in our setup to a build failure.
Override that for our 5.4 kernel setup.

Prevents for imx-vpu-hantro build:
| decoder_sw/software/linux/dwl/dwl_linux.c:53:10: fatal error: linux/ion.h: No such file or directory
|    53 | #include <linux/ion.h>
|       |          ^~~~~~~~~~~~~

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>