machine: toradex-smarc-imx95: fix ramdisk load address for FIT image
Move the ramdisk load address 32MB ahead to prevent a memory overlap
between the kernel FIT image and the ramdisk. This is relevant when a
FIT image is in use such as with the Secure Boot images.

Originally the ramdisk (present inside the kernel FIT image) had a load
address of 0x9c800000 which was the same address where the FIT image
itself was loaded (as set by the ramdisk_addr_r variable in the U-Boot
environment) causing the following error during boot:

  ## Loading kernel from FIT Image at 9c800000 ...
     Using 'conf-freescale_imx95-toradex-smarc-dev.dtb' configuration
     Verifying Hash Integrity ... sha256,rsa2048:dev+ OK
     Trying 'kernel-1' kernel subimage
       Description:  Linux kernel
       Type:         Kernel Image
       Compression:  gzip compressed
       Data Start:   0x9c8000f0
       Data Size:    11490846 Bytes = 11 MiB
       Architecture: AArch64
       OS:           Linux
       Load Address: 0x94400000
       Entry Point:  0x94400000
       Hash algo:    sha256
       Hash value:   6ab94247f1d57073...
     Verifying Hash Integrity ... sha256+ OK
  ## Loading ramdisk from FIT Image at 9c800000 ...
     Using 'conf-freescale_imx95-toradex-smarc-dev.dtb' configuration
     Verifying Hash Integrity ... sha256,rsa2048:dev+ OK
     Trying 'ramdisk-1' ramdisk subimage
       Description:  initramfs-ostree-torizon-image
       Type:         RAMDisk Image
       Compression:  uncompressed
       Data Start:   0x9d331c90
       Data Size:    13004129 Bytes = 12.4 MiB
       Architecture: AArch64
       OS:           Linux
       Load Address: 0x9c800000
       Entry Point:  unavailable
       Hash algo:    sha256
       Hash value:   88544e571c46aea0...
     Verifying Hash Integrity ... sha256+ OK
  Error: ramdisk overwritten

With the change in this commit, the memory layout when a FIT image is in
use becomes this:

0x94400000 (2G+324.00M): kernel load address
0x9c400000 (2G+324.00M + 128.00M): DTB load address
0x9c440000 (2G+324.00M + 128.25M): DTBOs load adress
0x9c800000 (2G+324.00M + 132.00M): kernel FIT image (ramdisk_addr_r)
0x9e800000 (2G+324.00M + 132.00M + 32M): ramdisk load address

Related-to: TOR-3932
Fixes: 7df2642e3c63 ("machine: toradex-smarc-imx95: add fitimage variables")
Signed-off-by: Rogerio Guerra Borin <rogerio.borin@toradex.com>
(cherry picked from commit 5a87d66079e1878229bfc8dba9d750e6d2f0be90)