colibri-imx6ull-emmc: fix fitimage ramdisk load address
Booting with a FIT image (that includes a ramdisk image) is failing with
the following error:

Error: ramdisk overwritten
Ramdisk image is corrupt or invalid

This is because the boot script uses ramdisk_addr_r to load the FIT
image, and this is overlapping with the default fitimage ramdisk load
address.

Fix by adjusting the fitimage ramdisk load address:

UBOOT_RD_LOADADDRESS = ramdisk_addr_r + 32M

Signed-off-by: Sergio Prado <sergio.prado@toradex.com>
(cherry picked from commit cb0a04aa51d2036aa6e4af6fdc92c1cc1d5935e8)