btuart: fix overrides
Turns out that somehow we still have some old override syntax stuff
laying around!

This resulted in the following build error:

ERROR: btuart-1.0-r0 do_package: QA Issue: btuart: Files/directories
 were installed but not shipped in any package:
  /usr
  /lib
  /usr/sbin
  /usr/sbin/btuart.sh
  /lib/systemd
  /lib/systemd/system
  /lib/systemd/system/btuart.service
Please set FILES such that these items are packaged. Alternatively if
 they are unneeded, avoid installing them or delete them within
 do_install.
btuart: 7 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>