xorg-xserver: remove duplicated patch
The patch 0003-Remove-check-for-useSIGIO-option.patch has been added to
xorg-server recipe on meta-freescale layer [1].
Reapplying this patch causes the build error [2].
Remove this patch from the meta-toradex-nxp layer.

[1]
07d4a6baa23ec3a1f013f8a070130598b56aec7c
xserver-xorg: Backport to fix X server 1.20.1 crash [YOCIMX-3280]

[2]
------------------------
ERROR: xserver-xorg-2_1.20.1-r0 do_patch: Command Error: 'quilt --quiltrc
  /oe-core/build/tmp/work/armv7at2hf-neon-mx6qdl-tdx-linux-gnueabi/
  xserver-xorg/2_1.20.1-r0/recipe-sysroot-native/etc/quiltrc push'
  exited with 0  Output:
Patch 0003-Remove-check-for-useSIGIO-option.patch is already applied; check your series file
------------------------
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@toradex.com>