Revert "verdin-imx8mp: use dedicated wks file and add space to the wic rootfs"
This reverts commit 4087b01cd5c70f4656cdff26a4e7d7ecc73bf41f.

Now with the Toradex Easy Installer for the Verdin iMX8M Plus just
around the corner get rid of this again to avoid the following Easy
Installer build failure:

NOTE: recipe tezi-initramfs-5.3.0-devel-r0: task do_image_squashfs:
 Started
ERROR: tezi-initramfs-5.3.0-devel-r0 do_image_squashfs: The initramfs
 size 1180604(K) exceeds INITRAMFS_MAXSIZE: 160000(K)
ERROR: tezi-initramfs-5.3.0-devel-r0 do_image_squashfs: You can set
 INITRAMFS_MAXSIZE a larger value. Usually, it should
ERROR: tezi-initramfs-5.3.0-devel-r0 do_image_squashfs: be less than
 1/2 of ram size, or you may fail to boot it.

Signed-off-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>